### ISSUE TITLE
Add scss-lint custom config to project directory

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Front-End-Toolkit#35]
Easier to set up: http://prntscr.com/8dwkw3

**Comment by VaclovasV** [comment]
add .scss-lint.yml file to project root with scss-lint config

**Comment by linasmatakas** [comment]
Project root is where you open your webstorm project in this case(functionality allowing it to place anywhere in the project was removed at some point).

There are alternatives to place it in user's home directory or use gulp task to output summary of scss code lint warnings in gulp task interface or file.

gulp task output:
![image](https://cloud.githubusercontent.com/assets/10974201/11337542/77a298ba-91f6-11e5-8bc8-4bcda6513a00.png)

config file can be simple since it just overrides default properties:
linters:
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 4

Any preferences on further actions:
1) place config file in 'starter-template'.
2) instructions to place config in user's home directory.
3) gulp task.

**Comment by VaclovasV** [comment]
I think, we should add it to the same level as gulp file

**Comment by linasmatakas** [comment]
Proceeding with option 1 - 'starter-template' folder, also where gulp file is.

config contents:
linters:
  Indentation:
    width: 4

branch: release-1.0.1

Leaving task open to discuss changes during meeting.
