### ISSUE TITLE
Add editorconfig to prevent issues, then IDE is configured differently per developer

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Front-End-Toolkit#37]
More info - here: http://editorconfig.org

**Comment by linasmatakas** [comment]
What kind of issues?

**Comment by VaclovasV** [comment]
Possible issues:
different newline ending
default charset
indentation
indent style (normal and special files, like package.json)

**Comment by linasmatakas** [comment]
couple of notes on .editorconfig:
# .editorconfig would override any other settings you have on IDE.
# need to turn on .editorconfig usage in webstorm settings.
# can target file types, files, exclude files, can have more than one config(supports hierarchy/folders).

It seems that issues appear after screwing up default settings.

I am not sure what's the point of forcing settings through .editorconfig. We could achieve minor code style unification with this, but making a config to define these code styles that works for everyone is kind of hard, since I do not think that we can force global settings - f.e. 4 spaces indentation on all files, because . json files has 2 spaces by default and I think that automated tools would output with 2 spaces indentation. I am pretty sure we could find other exceptions.
Other scenario would be to have poor config, which has basic defaults that should not be touched in the first place.

Lets discuss this during meeting, perhaps there is something important that I do not understand at this point.

**Comment by VaclovasV** [comment]
Situation: big project, lots of team members, different IDE
Problem: how to setup everything for each team member + if team decides to change rules, how to sync settings without any effort?
Solution: add editorconfig file. 
Is it a real problem? Like in grainger, we already have lot of developers and they are using 3-4 different IDE (webstorm, VS, sublime, codekit)
What about forcing global settings for every file?
You don't have to force global settings, you can define settings per file format.
Like, if you want to add special config for a package.json file, you just have to add: http://prntscr.com/99a1in

I think, essential things are:
charset
indent style
indent sizes
newlines
end of lines

We should agree on rules and add them to config.

**Comment by linasmatakas** [comment]
Added .editorconfig file to branch: release-1.0.1

Do not forget to enable editorconfig in webstorm.
![screenshot_3](https://cloud.githubusercontent.com/assets/10974201/11589750/95454476-9a93-11e5-9e3e-bad2a7adf1ec.png)

@VaclovasV define editor settings.
