### ISSUE TITLE
Add rule, to ignore tmp*.scss files to prevent compiling errors/warnings

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Front-End-Toolkit#40]
How to:
https://devbridge.atlassian.net/browse/PM-128

**Comment by linasmatakas** [comment]
While testing 'gulp-ignore', I realized that we do not need to gulp.src() all SCSS files when compiling and can do: `gulp.src([config.scss.scssFolder + 'site-styles.scss'])` - it imports other files anyways. We need to keep watch on all SCSS files, but that does not seem to cause problems. 

Do we prefer to: 
1. build all scss files and ignore scss-lint files
2. build specific scss files, but have to specify it if there is more than 1 ?

**Comment by VaclovasV** [comment]
@linasmatakas 
what are advantages of 2nd option? 
I would go with safe option - just exclude what is not needed. 
Implementation can change, behavior can change, so picking only files, which are not needed would be a safe option.

**Comment by linasmatakas** [comment]
@VaclovasV 
In my opinion, 2nd option is safer - no dependency on extra gulp plugin which might change or become incompatible with latest node, gulp or sass, you target exactly what you need and we usually need 1 file.

**Comment by VaclovasV** [comment]
@linasmatakas 
and how sass watch will be triggered, if we will target 1 file?

**Comment by linasmatakas** [comment]
@VaclovasV 
watch and compile are different functions.

**Comment by VaclovasV** [comment]
@linasmatakas 
i will describe shortly the problem
Problem:
1. You are watching scss directory then watch is launched
2. scss-lint creates temporary files inside this directory and sometimes generated files causes errors/warnings (if not totaly clear, about what I am talking, ask Vitalijus, we already solved this issue on his project), because they are included in watch task. This is rare case, but sometimes this is very confusing.
3. ignoring tmp.scss files resolves this issue
are we talking about same thing?

**Comment by linasmatakas** [comment]
@VaclovasV 

Yes, the same thing.

Error happens in compile function which is called by watch, and when compile function fails because of scss-lint temporary files then watch crashes. So, gulp-ignore solves the problem by excluding temporary files from compilation pipe. While we can compile specific files such as site-styles.scss instead of all files which usually are only site-styles.scss anyways and if we need more files, we can specify them. 

Note that the problem is solved in exactly the same place.

And our choice comes to:
1. Extra node module 'gulp-ignore', which would compile all SCSS files without requiring us to specify which files to compile, solve our current issue, but leave very small chance of bumping into similar problem or node module incompatibility with some node or gulp versions.

2. Specifying files to compile - f.e. site-styles.scss. Note that we do not need to specify imported files in gulp config for compilation. Gulp watch would still work on all SCSS files, but temp files would not get compiled and not produce errors, because they would not be specified to be compiled and not imported by any SCSS files that would be compiled.

**Comment by VaclovasV** [comment]
@linasmatakas 
Long story short, here is an example:
 https://bitbucket.org/devbridge/prototype-camelot/src/3103b93cde89597ddd8e0644771d722e7f9e3adc/gulp/gulp.config.js?at=master&fileviewer=file-view-default

**Comment by linasmatakas** [comment]
Added gulp ignore and changed config.
https://github.com/devbridge/Front-End-Toolkit/commit/6aed28f253b893cc4a564c92b9f775ab37de3097
