### ISSUE TITLE
Update Scss folder structure

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Front-End-Toolkit#62]
Current structure is too complicated. My recommendation is to simplify it:
![screenshot at jul 01 18-12-58](https://cloud.githubusercontent.com/assets/10126531/16525967/a2e77152-3fb7-11e6-9c3d-f45c0b49912c.png)

**Comment by VaclovasV** [comment]
Perfect, just I would add mixins to base/core

**Comment by andrius1** [comment]
I like splitting the mixins.
However, "components" and "modules" looks confusing. I mean what's the difference between checkbox and promo banner? Both are (should be) reusable modules. I would rather have separate folder for layout (header, footer, sidebar, etc). Because layout components are not reusable - they are used once and never will be used inside any other module.

**Comment by VaclovasV** [comment]
Fixed in v2-dev
