### ISSUE TITLE
Review javascript structure

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Front-End-Toolkit#8]
We need to review existing javascript structure:
1. We need to add references to CDN resources with appropieate fallbacks.
2. We need to check for latest versions of the libraries.
3. We need to check if new libraries needed in default templates.
4. Predefined default modules for plugins initiation in site.js file (like module.modal = function(){..})

**Comment by VaclovasV** [comment]
Do we have to update jquery version?
Performance comparison: http://jsperf.com/speed-comparison-of-jquery-versions/16

**Comment by gediminas-s** [comment]
We can stick with the older version for now.

**Comment by VaclovasV** [comment]
-1. We need to add references to CDN resources with appropieate fallbacks- Done
-2. We need to check for latest versions of the libraries- Done. Validate library isn't updated because of compatibility with validation unobstrusive.
-3. We need to check if new libraries needed in default templates- I think, that template should be as sleek as possible. If team thinks differently - let's discuss what libraries are needed.
-4. Predefined default modules for plugins initiation in site.js file (like module.modal = function(){..}) - Added default validation, mirroring validation unobtrusive default configuration, modal default initiation, added descriptions, documentation links and examples of libraries in template.
